#! /bin/bash

#OSX Command line tools
xcode-select --install

# JENV
git clone https://github.com/gcuisinier/jenv.git ~/.jenv

# Checkout dotfiles
if [ ! -d ~/code/dotfiles ]
then
	echo
	echo "Cloning dotfiles repository"
  mkdir -p ~/code
  git clone git@github.com:samlawrencejones/dotfiles.git ~/code/dotfiles || echo "Generate/Upload SSH Key To Github: https://help.github.com/articles/generating-ssh-keys/"
fi


# Install Homebrew
if ! which brew >/dev/null
then
	echo
	echo "Installing Homebrew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Install Homebrew tools
brew install wget git vim zsh heroku-toolbelt ripgrep cmake tree gpg hub editorconfig git-imerge jq fzf zsh-completions bat exa
brew tap heroku/brew && brew install heroku
echo
echo "Installing python"
brew install python
sudo easy_install pip
brew install python3

link() {
    ln -fs ~/code/dotfiles/$1 ~
}

# Link files
link ".tmux.conf"
link ".pryrc"
link ".rspec"
link ".vimrc"
link ".gitconfig"
link ".gitignore_global"

# Install spacemacs
# brew install emacs
# git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
# link ".spacemacs"

# Install Ruby
brew install rbenv ruby-build rbenv-default-gems rbenv-ctags rbenv-bundler-ruby-version rbenv-gemset rbenv-binstubs brew-gem
brew gem install bundler
brew gem install pry
brew gem install pry-doc
brew gem install pry-nav
brew gem install pry-stack_explorer
brew gem install gem-ctags

# Install node
brew tap nodenv/nodenv
brew install nodenv node-build nodenv-package-json-engine nodenv-default-packages
ln -s default-packages $(nodenv root)/default-packages

# Install GVM
if ! which gvm >/dev/null
then
	zsh < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
  source /Users/sam/.gvm/scripts/gvm
	gvm install go1.4 -B
  gvm use go1.4
  export GOROOT_BOOTSTRAP=$GOROOT
  gvm install go1.6
  gvm use go1.6 --default
fi

# Install prezto
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
link ".zshenv"
link ".zshprofile"
link ".zshrc"
link ".zpreztorc"
link ".zshlogin"
link ".zshlogout"

# Install Haskell stuff
echo
echo "Install haskell platform"
brew cask install haskell-platform
echo
echo "Install haskell stack"
brew install haskell-stack
stack install hlint ghc-mod
echo
echo "Install Complete"

# Install Elm stuff
echo
echo "Install Elm"
brew cask install elm-platform
npm install -g elm elm-oracle

# Install Elm stuff
echo
echo "Install Elixir"
brew cask install exenv elixir-build erlang

# Tmux
brew install tmux tmate reattach-to-user-namespace

# Fira Code Ligature Font
brew tap homebrew/cask-fonts
brew cask install font-fira-code
