#! /bin/bash

#OSX Command line tools
xcode-select --install

# JENV
git clone https://github.com/gcuisinier/jenv.git ~/.jenv

# Checkout dotfiles
if [ ! -d ~/code/dotfiles ]
then
	echo
	echo "Cloning dotfiles repository"
  mkdir -p ~/code
  git clone git@github.com:samlawrencejones/dotfiles.git ~/code/dotfiles || echo "Generate/Upload SSH Key To Github: https://help.github.com/articles/generating-ssh-keys/"
fi


# Install Homebrew
if ! which brew >/dev/null
then
	echo
	echo "Installing Homebrew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Install Homebrew tools
brew install wget git vim zsh heroku-toolbelt the_silver_searcher tmux wemux cmake ctags tree keybase gpg hub emacs editorconfig
echo
echo "Installing python"
brew install python
sudo easy_install pip
brew install python3
echo
echo "Installing neo vim"
brew install neovim
sudo pip install neovim
sudo pip3 install neovim

# Install applications
echo
read -p "Install brew cask applications? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  brew cask install google-chrome firefox gitter slack evernote atom alfred seil bettertouchtool iterm2 the-unarchiver skitch dash dropbox docker-compose
  open -a Dash
  open -a Dropbox
fi

# Install Oh My Zsh
cd ~
if [ ! -d ~/.oh-my-zsh ]
then
	echo
	echo "Installing Oh My Zsh"
  sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
  zsh
fi

# Install vundle
if [ ! -d  ~/.vim/bundle/Vundle.vim ]
then
    echo
    echo "Installing Vundle"
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi
vim +PluginInstall +qall +PluginClean

link() {
    ln -fs ~/code/dotfiles/$1 ~
}

# Link files
link(.tmux.conf)
link(.pryrc)
link(.rspec)
link(.vimrc)
vim +PluginInstall +qall +PluginClean
cd ~/.vim/bundle/vimproc.vim
make
link(.gitconfig)
link(.gitignore_global)
link(.ctags)

mkdir ~/.vim/doc
cd ~/.vim/doc
ln -s ~/code/dotfiles/mytips.txt .

# Install spacemacs
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
link(.spacemacs)

# Install Ruby
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -sSL https://get.rvm.io | bash -s stable --ruby
gem install bundler pry pry-nav pry-stack_explorer pro-doc ruby_parser rubocop gem-ctags

# Install node
brew tap nodenv/nodenv
brew install nodenv node-build nodenv-package-json-engine

# Install GVM
if ! which gvm >/dev/null
then
	zsh < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
  source /Users/sam/.gvm/scripts/gvm
	gvm install go1.4 -B
  gvm use go1.4
  export GOROOT_BOOTSTRAP=$GOROOT
  gvm install go1.6
  gvm use go1.6 --default
fi

link(.zshrc)
link(.myzshrc)

# Install Haskell stuff
echo
echo "Install haskell platform"
brew cask install haskell-platform
echo
echo "Install haskell stack"
brew install haskell-stack
stack install hlint ghc-mod
echo
echo "Install Complete"

# Install Elm stuff
echo
echo "Install haskell platform"
brew cask install elm-platform
npm install -g elm elm-oracle
